name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-css:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Node.js dependencies
      run: npm install

    - name: Run CSS lint
      run: npm run lint:css

  lint-js:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Node.js dependencies
      run: npm install

    - name: Run JS lint
      run: npm run lint:js

  lint-md-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Node.js dependencies
      run: npm install

    - name: Run Markdown docs lint
      run: npm run lint:md:docs

  lint-php:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Node.js dependencies
      run: npm install

    - name: Install Composer dependencies
      run: composer install --no-scripts --no-interaction --prefer-dist

    - name: Run PHP lint
      run: npm run lint:php
