name: Fix PHP Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-php-fix:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.head.repo.fork && github.actor != 'github-actions[bot]' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer dependencies
      run: composer install --no-scripts --no-interaction --prefer-dist

    - name: Run PHP lint fix
      run: vendor/bin/phpcbf || true

    - name: Commit fixes
      run: |
        if git diff --quiet; then
          echo "No changes"
          exit 0
        fi

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Fix PHP lint issues"
        git push
